docs: add documentation for YAML anchor extend feature
Mergifyio/docs pull request #3312
Opened 2024-01-26 15:11 UTC by Syffe

Following the implementation of the YAML anchor extends feature, we needed to add to corresponding documentation.

Fixes MRGFY-3183

2024-01-26 16:21 UTC, jd requested changes

2024-01-26 16:21 UTC, jd commented on src/content/docs/configuration/sharing.mdx
> +  - If you define the same anchor in both files, with different values,
```suggestion
  If you define the same anchor in both files, with different values,
```

2024-01-26 16:21 UTC, jd approved these changes

2024-01-29 10:31 UTC, DouglasBlackwood approved these changes

2024-01-29 10:34 UTC, merged